seed: 1
network: 'resnet18'
pre_train: True
v_hdim: 1024
z_dim: 64
bs: 64
lr: 1.e-4
epochs: 80
shuffle: True
augment: Falses

save_model_interval: 10
imsize: 224
loss: 'VAELoss'

# if you wanna train from scratch, please set off this key: init_train
checkpoint: 'results/model_resnet18/sequence/models/ckpt_train_41.pth'
init_train: True
eval_metrics: 'mse' #'cos'
