seed: 1
network: 'resnet18_simCLR'
pre_train: True
#projection dims of SimCLR
z_dim: 64
bs: 64
lr: 1.e-4
epochs: 80
shuffle: True
augment: True

save_model_interval: 1
imsize: 224
loss: 'NT_Xent_MSE'
NT_Xent:
  temperature: 0.5

# if you wanna train from scratch, please set off this key: init_train
#checkpoint: 'results/simCLR_resnet18/sequence/models/ckpt_train_30.pkl'
init_train: True
eval_metrics: 'mse' #'cos'
